# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-anime-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:rRUNjqfjRdoWnuzZRxExTKUxJizOPRT10Vw+Xiu5MDE=,iv:sgKxoA/oZQXn/rD7kJamO3hMfjsQYSKxBhs2IwkUmi4=,tag:3WbEJfjrEJOWHB6WFSfbWw==,type:str]
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:a8O8AUpmURE3/co8ccVmbgRwRZcbfw/apk+dsPi7/0ZvPQOQbOc=,iv:TAVUTc7UpBanzIP8WGWt6OQV31vKIg1effmkCWUdaq0=,tag:pOH1y/iLwPXGauC0PhRPdA==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:1n3OVw==,iv:Yi/hNqTQqgcJQhmJJUf3QlJjhdYpPZM8BsFOZBcirAQ=,tag:POxpZOVW6TKy9AK1EAn7Gg==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:pM+GwmUiskI74nCa,iv:Ed6CsbG6fuz8N0pXPvMkZZdRixcxx1M38z90ws4F2xk=,tag:+IaLYSwgtSNh5aI2coHkmQ==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:4+0QDUHTTKADSvxUglDa1gQepgfevzcpSTOrJ2sn2VkiaUZSGAKcntwo5TU=,iv:vYTeEGK2k9F071q2/WE1EFL44BiC4TCEtFdbjGOMBl4=,tag:lnaMUYvQ4bb2tgDJbCFRtw==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:YQyneci5DHDtExAXkNNHT3E=,iv:UfyQMd4jew05CpzdtWOulXf/ZKBcVduZgatUZC7KX+I=,tag:Fe0fr/7VDgbqz8wgYxCT/Q==,type:str]
  SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:R3f+l4bLu3cFXkzKUpOthg==,iv:oLBRl5bN8o2wFNhbj6/HBeT1Mqfzww+HXdu+RTj0plA=,tag:exB18CpcpHF17mp5BTK15w==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:YARtF5cAa/PaFrrPHdOuGMBmoeYcE/v1RKaJVynPusXCIQ==,iv:OkcbbFaPnQIeaiCpN8YKEXeHAH+s0ufAiY7JtE7Mp1Y=,tag:Y+fhbevjSIzexhQQOSDKIA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:qCfQKPZeBzTr7GY8HPckBwJ9CscSY6SCa+UZxfNw5CNlo432dPU=,iv:9uuk5jcgw9xCgxos2YzAUaMWQDuT8CnQbwKO0UJl+1c=,tag:ww7y6TwfgPdL5kOpQnk27A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZbfBAjlCgZgQic86,iv:1yRJcukP5ZhC6md7gBJOXmZe+U+aD7fihc6gBShHyQ4=,tag:YRQOHTHIMv14JZ3xKQ7ZqA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:3WaseQEPVlHvIvc8/+oZ/1TCk5oDgVnJCHB8f/FVnjJgYK9YiQJ3aaqTnRE=,iv:4iILzsQxm1DSU+LXCjphAAI9lDWVhnp4RD7mBJJIpUI=,tag:pooU9aVI/EZWv5xTqoszVA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Jop+gP64Mibq9KlkKgfc5+//17hdXi6dNW78O6kU/0AkuT24ZYuxnXXqZYw=,iv:ZeJeFp6sM0CaFFnRPRCR0YNceM4Ed1A3/KjNrGfOUWw=,tag:l2gE34q0KVcYY2dZ2fZk9A==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd0xTOXRJcE1IaWpHWjI3
        VUMxdEkrNXhxZ1IzaFl0U2tYb2dYQWtzQlhZCkNMUDdFRExHWDFGYlYrOENid09Q
        LzEwUXlPOEYyeDlDcU9xK1Z5L1czUWsKLS0tIFpmUHgzYWY4SERrRmJvM2RhUUlz
        bzVDTXo0RFZUQk9pNDJpQk1xREdLSDQK8ZMF6xiah9bwFsLIiup8ax09RGGUSxyn
        E94t9s8PdOeLdcfx4wUKUGjIuL1WAN77dxkVGoAseHxRgdpRK/4PFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:23:44Z"
  mac: ENC[AES256_GCM,data:b/capt/T0o/e8myMVIEqGH690ZvNI/TJyh3c8ATWtYvQg1br8kPTTS2y5psTGIVciI1RWFG0wm5ICmvKvJ+CbiQJ7+Xqqgap8j5t81Ax4KRQr/polft+nQ9pVONhTNvG0oOU4h/CsajjX2MYea7WBAxcvBIenLLzIJd9CuK6pt8=,iv:wJcezynYXs1pOjGk9r362nCmjxLByXsS4sdbSmTA/6w=,tag:2e8gTwwZWvdl2wKfnFiaYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
