apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres-16
spec:
  retentionPolicy: "15d"
  configuration:
    destinationPath: "s3://postgres/"
    endpointURL: https://81e69641b977773fe31b62d05f0b44e3.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cloudnative-pg-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: zstd
    data:
      compression: bzip2
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres
spec:
  retentionPolicy: "7d"
  configuration:
    destinationPath: "s3://postgres/"
    endpointURL: https://81e69641b977773fe31b62d05f0b44e3.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cloudnative-pg-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: zstd
    data:
      compression: bzip2