# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: slskd-secret
stringData:
  SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:nmziW1BjeGnl5w==,iv:1OZU5CZAnfoIKhHQqevdCARIurKCnHX6oNIAqkxHIcw=,tag:aXIvKlhhf//rRCsn1IlfiA==,type:str]
  SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:wPwFoiSDLkomSsE=,iv:ViVR/aOL0gppo5QNTu+P6iw3FYatP2awUjs+mXHlxgY=,tag:gDrypRaILMiW6gMSFULY3w==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR2M4V3MxM1IySjZVYzFT
        UmI4WFR0SUdyZVVYZTRNaTMvSHZQVFZhVUVrClpzcTk5OXkzUVdsRS91YlNrRDUr
        TkozK3JKU0N6TVJoeWFQUUNsOU5LU0kKLS0tIHFTbVk4S1FOY0Vid3ZhcVpjVnNx
        dDdkRFZOQUdFaHRNbkowSWdCajZYODAKzFCEedm2YherPAFe3FBX+aprnb4Hl+kg
        P0EOl/KCRu6rbPdu1Twb+UxGuLssjF4Ek0MYSFhhM9MUG/1aicsDJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T09:01:22Z"
  mac: ENC[AES256_GCM,data:QgEurfnCM540g7bKT+ISiRpRuh9GqGFP6I8FbGVVCwPSaLeolqQT7wtz1YNUMiOFQB8WXDrm1+jKqcWU/JuJh2do4r1jxMj6q9fv4dRka/0YmMSIbkNl1wUHHvMDyYVXYVOMVoVOaC+UHK/IHm4Fo8e3/njJz2J0rb8mI7sWPSQ=,iv:kkeyW0Ho+hPjsM30pxtk+3H5Sh+dtpkDvg+QnURXbr8=,tag:AlbMCryvFqUYqylX94pgvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
