---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: filebrowser
spec:
  interval: 30m
  path: ./kubernetes/apps/media/filebrowser/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../flux/components/volsync
  postBuild:
    substitute:
      APP: filebrowser
      VOLSYNC_CAPACITY: 1Gi
  targetNamespace: media
  timeout: 5m
  wait: false
