apiVersion: v1
kind: Secret
metadata:
  name: seerr-secret
stringData:
  API_KEY: ENC[AES256_GCM,data:jTBGuyvUX5BQ1pzmR6mySQ2HruLoXAQC2sXl6Y8B/jfDRp3Oxek8f3Lw/60=,iv:xdM0jNCZUKsL6RMHzy6DoHITMkMf+r3ZmloS5XF1kPs=,tag:tsy+vi4H3WIJtFxzO4IJaA==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeEJJTDRQb0N3OU9YZVFZ
        LzdlaFhZY2RUTCsvMDhWMVVEUXU1K3ErMkJRCkVhSjB0c2dhNVJweWxNSVJiN05x
        WVpybXVhRDFYZ2N6SmkyN1ptVE1kUDgKLS0tIEhqODVVUDF2QVlZUWxaUUxlQVhs
        WW1maS9Tc0t5RmNVSkl6VDZqL04ySjAK/9828WzAaJ+WCd+ZtvVyAtSjxGW7jnxF
        K9yv4rTEndnOdMNBPOFRGm4aSnRHV4Xb8fSPBtk6l3xYXCIadO3t3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T10:40:23Z"
  mac: ENC[AES256_GCM,data:yN2I02KEJ1WlzjQVjxRKNABnjpcL/xdPUKoSl+HwjnCD6gCqDy8YW2GU7ii/Z0zzOhbntzRbexsUn3IsW78R25VWaz74zRNgyoqvswHxYIGOpIbdGHOBPQzLCyP/p3C7z+Mzst0+R95e2NCegOiYmdm8RhjNLqtbK+zJcT2d+Fg=,iv:0WXS2Z6OYU9YTWsVRUbwsum41PH2HtgJ6080uZCWdOg=,tag:2agbGRTKo7G2qj1q+vLQig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0