# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:TNipu39lGkXilox9c2tRYRSYjdSrEVROCBkN5dBU6HI=,iv:KkoV5mnVvAl30q/d8J+Du8F3KSKm2V0SqrGrYrFKZt8=,tag:j4pcZknrw5K2WLr6uesVrQ==,type:str]
  PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:zw65rMK5DC3UwIaC9QTOE6A5mPftqIDmma6Uy7jIibXeloT8mB0=,iv:o4uiEOEc3/Ju+dTAUMAW+O2UiuXWZHmdkxb+HPIFBLM=,tag:Kc3TP0NPzG6/LpQU5h9Lzw==,type:str]
  PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:HQSdqw==,iv:vwFywvakFW04hZRuEZYTkCdMsOMjNXemJ6uxh4Z65ME=,tag:TBWey6mgxI9lPY46tgG/rg==,type:str]
  PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:dKpVMwOzhO8=,iv:nu4aFmr96jsxrg/dnAbrJaDSDifNSn1lQh5jfgwb6RM=,tag:s3oRwTRDfT0rKCKSxGmblQ==,type:str]
  PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:gNjzU/lBNIvRWXE=,iv:1ZSIqaU8+JVqxu5XK/PN4jzTWcKvuYBPlGvIS7Uphco=,tag:kWxEZc5nnpzcV47pZI+dEg==,type:str]
  PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:3/ug9Gy6lcEMyCPpgQ==,iv:V+M470+EzqqDSsbxSzFMr/BtSH86yf9N8URkM2g+f2g=,tag:bnPtJu8rqiAWnnpQeZSHKg==,type:str]
  PROWLARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:SIoXBmWJj3RWMO6N,iv:/26nvq/7m1vLrGTycwfiaQ/N4F5Xbb4PwBaYjPyHn5o=,tag:5NfW7DMosNAVw68Ux9a4BQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2gdv/jczmhUvWjLif3OCY4oWOAS3Q4Lmx00=,iv:4BSUs4yPxG4NAzkpplnGBl6mIxX60BT61/2qG4Sa43c=,tag:Q3PL8EB18XtXuChiKXLFNw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:u7mypG/qJTJn4gjsSEpIvsTYA4I3Xea5yCmFyqj3b5rrYOhodL8=,iv:gTlZtmJlTEQA8JThZjCLWUgsQi6SSJjix5x309mYIts=,tag:YqhTeOWoYMQ5iApOW2Ffkg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:TPxiIuJUcO8=,iv:aAZgpKYriEZfDcxya2YF4IDKaQMFgbFhm9W4BAiB1g4=,tag:Kj9Cr4221kUCAl2lXaSyaA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qjvS3+15r8PfLNI=,iv:D4VFGLb2gkCgXDnM4zdmNQZBIXwlsmDv1QUKw7QTncg=,tag:3MbU2FRw1MrWdUShCybctg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:cCatvwg/SKg/Y4Q=,iv:ho9LkspYa4SKSeSoo96pMYxXR747Xps/SciRXrBbnMA=,tag:GLiHUqfqB1J42T8ZW5LLFA==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdXloYVlOam5SZVZ0Vjhh
        blUvMW9xc0NVcm9kL3dJcXRkKzIzN2h1TVJNCmRpYi9LKzJMamZKWU1KNzM5T1cv
        aFc5REhMeUVBeXRuSzBqS3RnVGh4bk0KLS0tIDh3QndQaDdTZEFoYTNHRWhkNUZS
        VXFOVXhPZ29oRmdZVzlZT3ZWTTBBeFkKwOzUnRTuwaSO2hJ+o+nhu6bgFKmNSxUt
        fAOjv7kjGnZcDUpO6eeRDpogl9BVJoe0DNDrueRUahIIeveze75Kpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T08:24:51Z"
  mac: ENC[AES256_GCM,data:Dlo65kCTi71YuM6RpoUT0hcsIEanDbd2VCWyg3nl91V84mN886j6rw6zHTKioetogpQO7m8Ec+b32rRH3kRaj6mQrW+gd1CwigF9Yq8NxLnGemDuU5eXMfoT0J+lQm6lXUKUXjnMKda5yfjfvErYqsqVWF3VQ0/A2PDXh0DwB7I=,iv:9MirBbqSnjw3xFRPV098h2QBC1eL6ZLtUss8WAVKKq0=,tag:RF1U8hrXnOUX7FvX1SnHPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
