# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:TNipu39lGkXilox9c2tRYRSYjdSrEVROCBkN5dBU6HI=,iv:KkoV5mnVvAl30q/d8J+Du8F3KSKm2V0SqrGrYrFKZt8=,tag:j4pcZknrw5K2WLr6uesVrQ==,type:str]
  PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:zw65rMK5DC3UwIaC9QTOE6A5mPftqIDmma6Uy7jIibXeloT8mB0=,iv:o4uiEOEc3/Ju+dTAUMAW+O2UiuXWZHmdkxb+HPIFBLM=,tag:Kc3TP0NPzG6/LpQU5h9Lzw==,type:str]
  PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:HQSdqw==,iv:vwFywvakFW04hZRuEZYTkCdMsOMjNXemJ6uxh4Z65ME=,tag:TBWey6mgxI9lPY46tgG/rg==,type:str]
  PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:dKpVMwOzhO8=,iv:nu4aFmr96jsxrg/dnAbrJaDSDifNSn1lQh5jfgwb6RM=,tag:s3oRwTRDfT0rKCKSxGmblQ==,type:str]
  PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:kmc1/ywHfme67mISOH7lciMaXv+LMRDPu1DLdsuOMhbQ+jPxok/JqcVQlV0=,iv:vWjMkpPLS7WA5SzS2j0VhMMkv44bvZuLDA3a1tkY5D4=,tag:1A5fiJ8LIZx56JkxQ+opoQ==,type:str]
  PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:3/ug9Gy6lcEMyCPpgQ==,iv:V+M470+EzqqDSsbxSzFMr/BtSH86yf9N8URkM2g+f2g=,tag:bnPtJu8rqiAWnnpQeZSHKg==,type:str]
  PROWLARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:SIoXBmWJj3RWMO6N,iv:/26nvq/7m1vLrGTycwfiaQ/N4F5Xbb4PwBaYjPyHn5o=,tag:5NfW7DMosNAVw68Ux9a4BQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2gdv/jczmhUvWjLif3OCY4oWOAS3Q4Lmx00=,iv:4BSUs4yPxG4NAzkpplnGBl6mIxX60BT61/2qG4Sa43c=,tag:Q3PL8EB18XtXuChiKXLFNw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:u7mypG/qJTJn4gjsSEpIvsTYA4I3Xea5yCmFyqj3b5rrYOhodL8=,iv:gTlZtmJlTEQA8JThZjCLWUgsQi6SSJjix5x309mYIts=,tag:YqhTeOWoYMQ5iApOW2Ffkg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:TPxiIuJUcO8=,iv:aAZgpKYriEZfDcxya2YF4IDKaQMFgbFhm9W4BAiB1g4=,tag:Kj9Cr4221kUCAl2lXaSyaA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:KmLA0Ip5lolE2zhO196WQ/cX8D50whJbODiYrYz5JUwPYo4lrQTTDIMYqAk=,iv:3yFQPXfRGWvDfJBGZ+0lPbfKib/If4kzI+5HnBvko3Q=,tag:uFrWEyCQbX0qmjDx3ZkD+g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:jp1CLrJbbw5pPsl1duNqzMzMllNvOlEzIQU4rDhyYK4eM/C+sjdRgDXiL4I=,iv:VSr7msA0CqqiPyPjIgNGFgiTER969Es7Jzkz0iJ0aH4=,tag:kWDhyHI1f1mcSacsTLkIGg==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdXloYVlOam5SZVZ0Vjhh
        blUvMW9xc0NVcm9kL3dJcXRkKzIzN2h1TVJNCmRpYi9LKzJMamZKWU1KNzM5T1cv
        aFc5REhMeUVBeXRuSzBqS3RnVGh4bk0KLS0tIDh3QndQaDdTZEFoYTNHRWhkNUZS
        VXFOVXhPZ29oRmdZVzlZT3ZWTTBBeFkKwOzUnRTuwaSO2hJ+o+nhu6bgFKmNSxUt
        fAOjv7kjGnZcDUpO6eeRDpogl9BVJoe0DNDrueRUahIIeveze75Kpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:19:37Z"
  mac: ENC[AES256_GCM,data:khrcZDbtpmssetc5NmZApEji+hr62/zOg2CEUZBzrgqWqXQ6mZU/VsEFkAw1s6t2X+IMsgGxpM+vrMd+o2xrM8XoMaGAYsyendWeqRimpvMWSiU82pkU20MV0709N79UB5GmURZ9FMQO0CAxF96pxUoV2ImQ+bljhkgQBmYPHuQ=,iv:ybBesiQHDvUbL+nVtYQUc9a58D8zMpwmZFZBw/UosTE=,tag:yvLCGKVhoCSxrHPfj89Rkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
