# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  SMTP_HOST: ENC[AES256_GCM,data:/XH/rcdAMH1BBWq1UrQ=,iv:WyUbyazy6+TeYbsZn0QI2i3ew85lGB8AN9ax5hDqbaw=,tag:bNw0MNlmokTlX5krznO+Ng==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:2Bqa,iv:f7Zr2NIbNItdoFNY/u68TIAL4P0QD9GIs00U2LMuYj4=,tag:d9KEgAK6cR0/B49aVckESw==,type:str]
  SMTP_FROM: ENC[AES256_GCM,data:CY5e6Nv3NRTC1pKqqUyablNi/Uy1LA==,iv:9GZTPhG+jaLlIv6e3jcoxFfGypD6F9xDnHFVoRb1ZyU=,tag:600w9IdDoSat4JCEbU3Jmw==,type:str]
  SMTP_FROM_NAME: ENC[AES256_GCM,data:lYJ7yQ+V8GaZjgE=,iv:VB9XhViD86fPnBC0z2pHSdNAhNKLRR7tHIBz6CQqMeo=,tag:M68KhSywr8SKcl88khf+mw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:DFuwYqBPqq3r6mWkOPpXEM2xpA==,iv:4rCsbFcObtkks22NZvwXdPPvZjQdq6SyDUgS1iBtAxI=,tag:b94EFVeyJ8mLZnPQR27q3A==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:4aRWzfIj1miXYga5e39eK+M0jQ==,iv:IYOlyy+84KfOxAAA3hMLclozyvfohijHPk+rKNJoE6Y=,tag:2PC5dIsbnK88eTift8nUuQ==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:3DrpRjBpFTr9dI/dLNxlqn5auXv4zxMUmtmrlvApw7PDUFvoAyCMQpY3aZCfD1vkBnXuzZoPk/ATpu3rvjXk4+WP4PGCjL0DHIzx/XJMpc1ZyfC6rwo5iTGr/XnIXPjL2p+RqvbS8jY4z5L/KA3ARiN50ep+z26lW7vXdEOyuwFUJA5nk541h+AWsg==,iv:Y8xoVPHARxw2JYLvXK1s7+ocVE5BrmDcG2iL4b35YNU=,tag:VRVlOG7/micAWe3hnYWSyg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:XolYZQwB0ZwqgYAaHYkqlHzal5RYWzMyD30Fxp7mbRFK5DsgRUV8xob2hUnpeKiQMBK5MaiwOhTETuxhgtGd212hS0ZMtwvlRKFCjggI3+ukSnl7r4v0jZefxeltq5XBLXMWTsfFSTuyQEdmITSGSHLyUjLgU8ZS,iv:o8BFN9+/HLvfNvyvOyCTfjENiPH8E3FxQ229vomqO+I=,tag:KTYBNMsWfc1TurxpmvWMFw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:EUCzDfLU/aVVhh4=,iv:7BLE1msL9wuK8AJwPKiOPAVjrK6Nzsekm8EE4orUgdQ=,tag:mKvNQDTmZZftsH8VJ2uvsQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:E8v6MnBHxGok//ffOnylDnpGEJV91eVxG7s6i/NkbZB9U/vidRc=,iv:+uXeEJmd3QCkPuX2QVcVYQXR3xoXVv3vXjZDh2O/gNA=,tag:iIPuexaBbZObvzRdfPngLw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:wMvh2+2BBsr0wWQ=,iv:oHUIBYQc5jY/zbqLf/ljmcDgz35GvwARuBo0WKsuHwc=,tag:a0tWzXwC2A2SZ99ARJbS6w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:+oOKT+K7f+dTS4lWChZmcolgpQWEod2SEvkhdxZ9cPBb9DXC40tgFF7HaRA=,iv:+gNzsfJcho3QQq2p34Pduiwltd+kF1MVTlMvk3kck8M=,tag:3KS7f8NG2kz6LvgQSr0+gA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:2xckhNnmyPO1PAyih4Z9igRXW7xl8eAvqjyMXHyaKuCuLVs5vHB99cCuPkY=,iv:KC9GVkFtDUtkHgeRdkLOmBBHCEMwnB1e6+GecowD9UA=,tag:F6FxJLP+PFzoBp0bEIvM/w==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYzJLY2NtWS9QaWxjTmRa
        NkJGVTN6ZFRYQ0twWjdZWjJlbmd0YlJoNmtzCjhQb2pmSDh2czFjUENqSVY5NzE4
        S2ttSmpDL2s3ZTg1L1NtdVpzZkx1M3MKLS0tIE9tMnpNV2lPeXR2S1VibVRHR0ZS
        cXNxL2JENVpGcW9VaVJ0anBSdWFHb2cKSmMQCei/Ghg4k8GUSq36JUfaFgr2ZEgQ
        3EEP2X/nxmN8SoGxPxO9KNRjMOCzMUSP3pH+qOPspDbQ8p+w/g879w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:24:46Z"
  mac: ENC[AES256_GCM,data:l+OSK8f5WoPxANjoumZCdA3GFpQ/f+QqxKiUa1Qe9e4tZMmOgouTPGvRdgjJvH3qFqzpBEVS0IQHUfZ+qNdf/nju5vpF3pB6No6CtJQUiv5o3UmedILonrPiNN9o/FLCe7RJkrwYh7lvN3ZryqR2YMkPLQrQxoyNYy/4+fbCbEk=,iv:WD860yj3nQhlGKYEC0y5v57fF3pNmxTmcVDkDaQdI/Q=,tag:QGPAJjHICAeOyExDXx+8fw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
