---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopia
spec:
  interval: 1h
  path: ./kubernetes/apps/volsync-system/kopia/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: volsync-system
  timeout: 5m
  wait: false
