# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  labels:
    cnpg.io/reload: "true"
stringData:
  password: ENC[AES256_GCM,data:K25bbHmn7ozpvQ548xW3SnPveK98oc8nGa1ppz0CBc050R66gR8CvBWEzsY=,iv:q6b68AIK/Ctd8eIjrVEZNa9aWi5SxoKjFAcnGXknjL8=,tag:LvpLNH0WKDTcODqH9HWS/Q==,type:str]
  username: ENC[AES256_GCM,data:Di2a+VI7uxY=,iv:HlHqXV7wBbkFE5G7AoX568xQWYryWWDQisqu6woHGVo=,tag:qQoSADwK2HUo7T0jUgFfBQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZpNeHKpMpAWGV9C+LIgKwNVErGafJ6YrOPOQ07ovUVw=,iv:H56raz6PAtqyGRFyFAjNEKvjGVBohGy6WI7a20g0Ado=,tag:fl3YIMLA3Sg8c6Si4bojxA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RMPi8QGvQg7Iio7nWXwE8fCY+ZYI+jABW6kGFBuYMXFX+uYlNMilg/6/J3MFdG812LaUE0pjIRQP1YgArq7KfQ==,iv:+zvgpJvS3PYhH5WFSJ/YuRfsBWU6ha1lE5nQws9vkXk=,tag:QT5I7vFFrLR1BMyN061LVQ==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcW5CMno3U0tTOFp0ZW9l
        bmt6UEFzZE1CQWpMUll0VmpEZlk0SVA4eG5JClhJVjErSXRsSFh6VU5KckpIN2M4
        ZUROUnUrSllzZDdXOU5OdWt6akZlM3MKLS0tIElVWFUyd3U1cDE1aSswMHBMZ2VR
        dVpnM3doUTgzNzdNdUZnSGU2Q0pvaEUKRzgSFt/WxQhTrYdRTgLYvve0PKo9aP/D
        hOJ0IJre2uwaLFLHTWir2sMf3XSyjQHDjGS/naALLG8E1pAFJybD4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:31:14Z"
  mac: ENC[AES256_GCM,data:1Q1eRCyxX57uOR8aLGGGFMt3u7seQOlt6IE37FFggUtcCiNBJy6XtEze9T5a7bQnczFcqFR+rYTXDT5CCj7dUsmpOyRmC8WIA8Tcu0fJCCume8ubhzuAYLf83meba9eJSAtq3hC3bXz6Y5fMNopSRYMZkkAbLmsUxl7h3yMmqlw=,iv:8G0ktuWHsymiULmHP/naNjngYJtsSBib5jLZcZAzvEM=,tag:zJCgvodP/qnCINpYs905EA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-dbi-secret
stringData:
  password: ENC[AES256_GCM,data:yUTpIPpVvY2kZPhPhZ4=,iv:GYIuta7DQ+hrMK0ntN4ZoK/dtV8gYQDOtKtpuw8cm7A=,tag:KkzY1tdvl/FBKWX6TL32VQ==,type:str]
  username: ENC[AES256_GCM,data:Di2a+VI7uxY=,iv:HlHqXV7wBbkFE5G7AoX568xQWYryWWDQisqu6woHGVo=,tag:qQoSADwK2HUo7T0jUgFfBQ==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcW5CMno3U0tTOFp0ZW9l
        bmt6UEFzZE1CQWpMUll0VmpEZlk0SVA4eG5JClhJVjErSXRsSFh6VU5KckpIN2M4
        ZUROUnUrSllzZDdXOU5OdWt6akZlM3MKLS0tIElVWFUyd3U1cDE1aSswMHBMZ2VR
        dVpnM3doUTgzNzdNdUZnSGU2Q0pvaEUKRzgSFt/WxQhTrYdRTgLYvve0PKo9aP/D
        hOJ0IJre2uwaLFLHTWir2sMf3XSyjQHDjGS/naALLG8E1pAFJybD4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:31:14Z"
  mac: ENC[AES256_GCM,data:1Q1eRCyxX57uOR8aLGGGFMt3u7seQOlt6IE37FFggUtcCiNBJy6XtEze9T5a7bQnczFcqFR+rYTXDT5CCj7dUsmpOyRmC8WIA8Tcu0fJCCume8ubhzuAYLf83meba9eJSAtq3hC3bXz6Y5fMNopSRYMZkkAbLmsUxl7h3yMmqlw=,iv:8G0ktuWHsymiULmHP/naNjngYJtsSBib5jLZcZAzvEM=,tag:zJCgvodP/qnCINpYs905EA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
