# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: autobrr-secret
stringData:
  AUTOBRR__SESSION_SECRET: ENC[AES256_GCM,data:rPhZGTQuFVnG1bMuwdWxxh4NAH8loGSpxHR49U4W5E2Ch+L9j9PTrKN9gZ4=,iv:dOwLRTq0N7A7YnJaMoOiKwAQr3dBLo9ICUianfMunPI=,tag:+FPkwkMrmKpg/KHCzprQiw==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OEp1OFFGenNKc1U5YklX
        VitRcGplR2p5cCtTMTNWZ1FaK01pU0RyampJClliditQc2o5NjZwY0RhZzRxdjcy
        YTBiWGI4TSsrMU5DNWRKcUZ1OHphbDgKLS0tIHhZOGhlUDROWk13Q1Vhd0JCbisw
        MFRvSzIwYk9lTGYzZDZ1VExhR2krZVUKHgVtmi7QPpO0xuFKa2XsOTT8Nhksj4KL
        6YUobDMtnRZ2Zo1+C/bJAvzujHhV1vnrTz5jkkVKHlmAr/+MJVgtPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T03:33:39Z"
  mac: ENC[AES256_GCM,data:Qkaf7TIv+kp2dscqzc0lRaP379CPie8yVZV7q3/zIIPZoBeuutUmdHtsIN/WE5IDI0a8tSMhwvaA2l/iM8uRW7M5vwTtfcGXNNqr3QSfNeAR6FWcMuLQjfWclx7stub6hezg/GbmAZrd9+uR+bkJQ1XXgOvg1GFtwTT3ExEjWKw=,iv:6FlhTbg3CYMenNmCC+EJvJs5xSaLqUNbcJQcWh1oZ7E=,tag:vZ+G9W/42SYdq9e80xsPVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0