---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  anime:
    base_url: http://sonarr-anime.download.svc.cluster.local:8080
    api_key: !env_var SONARR_ANIME_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      episodes:
        anime: default
        daily: default
        rename: true
        standard: default
      season: default
      series: jellyfin-tvdb
    quality_definition:
      type: anime
    quality_profiles:
      - trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true
    custom_format_groups:
      add:
        - trash_id: f4a0410a1df109a66d6e47dcadcce014 # [Optional] Miscellaneous
          select:
            - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
            - ef4963043b0987f8485bc9106f16db38 # DV (Disk)
            - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        - trash_id: 35fb4585dcd9e2a5ac732e4309f5a45a # [Streaming Services] Asian
    custom_formats:
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: "[Anime] Remux-1080p"
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: "[Anime] Remux-1080p"
            score: -1000

  series:
    base_url: http://sonarr.download.svc.cluster.local:8080
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      episodes:
        anime: default
        daily: default
        rename: true
        standard: default
      season: default
      series: jellyfin-tvdb
    quality_definition:
      type: series
    quality_profiles:
      - trash_id: c4cadd6b35b95f62c3d47a408e53e2f7 # WEB-2160p (Combined)
        reset_unmatched_scores:
          enabled: true
    custom_format_groups:
      add:
        - trash_id: f4a0410a1df109a66d6e47dcadcce014 # [Optional] Miscellaneous
          select:
            - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
            - ef4963043b0987f8485bc9106f16db38 # DV (Disk)
            - 1b3994c551cbb92a2c781af061f4ab44 # Scene
            - d7c747094a7c65f4c2de083c24899e8b # Freeleech
        - trash_id: 35fb4585dcd9e2a5ac732e4309f5a45a # [Streaming Services] Asian
        - trash_id: d920fd959d220306888f40b6f38e1578 # [Optional] Season Packs
    custom_formats:
      - trash_ids:
          - 5d9fd1b1e06cd8a475462f40214b7df6 # FLUX
          - d34870697c9db575f17700212167be23 # NF
        assign_scores_to:
          - name: WEB-2160p (Combined)
            score: 100

radarr:
  movie:
    base_url: http://radarr.download.svc.cluster.local:8080
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      folder: jellyfin-tmdb
      movie:
        rename: true
        standard: jellyfin-tmdb
    quality_definition:
      type: movie
    quality_profiles:
      - trash_id: 90a3370d2d30cbaf08d9c23b856a12c8 # SQP-1 WEB (1080p)
        min_upgrade_format_score: 100
        reset_unmatched_scores:
          enabled: true
      - trash_id: 64fb5f9858489bdac2af690e27c8f42f # UHD Bluray + WEB
        min_upgrade_format_score: 100
        reset_unmatched_scores:
          enabled: true
    custom_format_groups:
      add:
        - trash_id: 7fc2751eef7e6bdc70b74136e5e35c76  # [HDR Formats] DV (w/o HDR fallback)
        - trash_id: 1616617ab3a14397a2b2321bcbda44d1  # [HDR Formats] DV Boost
        - trash_id: b29413a7487478fe98228ce79e5689e4  # [HDR Formats] HDR10+ Boost
        - trash_id: 9337080378236ce4c0b183e35790d2a7  # [Optional] Miscellaneous
          select:
            - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
            - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
            - 182fa1c42a2468f8488e6dcf75a81b81 # Internal
            - 0d91270a7255a1e388fa85e959f359d8 # FreeLeech
        - trash_id: f4f1474b963b24cf983455743aa9906c  # [Optional] Movie Versions
          select:
            - 0f12c086e289cf966fa5948eac571f44 # Hybrid
            - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
            - 570bc9ebecd92723d2d21500f4be314c # Remaster
        - trash_id: 47f0d69750de9e16855915fa73bb7b08  # [Optional] SDR
          select:
            - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        - trash_id: b22449f789b16a4163b59f1b70cbc580  # [Streaming Services] Asian