---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr_anime:
    base_url: http://sonarr-anime.download.svc.cluster.local:8080
    api_key: !env_var SONARR_ANIME_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    custom_formats:
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0

      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0

      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: -1000

  sonarr_main:
    base_url: http://sonarr.download.svc.cluster.local:8080
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p

    custom_formats:
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
          - 23297a736ca77c0fc8e70f8edd7ee56c # Upscaled
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

      - trash_ids:
          - d7c747094a7c65f4c2de083c24899e8b # FreeLeech
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

      - trash_ids:
          - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback)
          # HDR10+ Boost - Uncomment the HDR10+ Boost line if you want to prefer HDR10+ releases
          # DV Boost - Uncomment the DV Boost line if you want to prefer DV releases
          # Uncomment both lines if you want to prefer both (DV HDR10+)
          # - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost
          # - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost
        assign_scores_to:
          - name: WEB-2160p

      - trash_ids:
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: WEB-2160p

radarr:
  radarr_main:
    base_url: http://radarr.download.svc.cluster.local:8080
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      - template: radarr-quality-definition-sqp-streaming
      # 2160p
      - template: radarr-quality-profile-sqp-1-2160p-default
      - template: radarr-custom-formats-sqp-1-2160p
      #1080p
      - template: radarr-quality-profile-sqp-1-1080p
      - template: radarr-custom-formats-sqp-1-1080p

    custom_formats:
      - trash_ids:
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced

          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 (2160p)
          - name: SQP-1 (1080p)
      
      - trash_ids:
          - b17886cb4158d9fea189859409975758 # HDR10+ Boost
          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
        assign_scores_to:
          - name: SQP-1 (2160p)

      - trash_ids:
          - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: SQP-1 (2160p)
