# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:9vWk7eu7cEbcoaAR8uBvh+daus7mKNeD0Qp7pUtfhSI=,iv:jPNoZ0CdAUiVhTm4MRUZXMenjSNHhVRLf5hl6/ewSF0=,tag:jGZWSQkcrDIN8kIFi8Z9+g==,type:str]
  RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:B/FoLTIabTd4yWGJA9kJdaeH4X4YefGwjo5OEVBku2H2lnIY0aU=,iv:2WfEfh7dmWJ2ORkAVpL1oov0NBW473tOjFmRj5HwhmQ=,tag:mMjWZqUkklndnM6C9uWmRQ==,type:str]
  RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:beSOeA==,iv:LTbAnfP35oLkTmsJTTodS1eGd+0dAwbaJtDO0fXroCw=,tag:hAQxXGREJrY5jl0UjdJesg==,type:str]
  RADARR__POSTGRES__USER: ENC[AES256_GCM,data:MdECNgp0,iv:F/rG+Eo3//VKGQVQj9dg3MM9w9IioPKUfmQTYZo8FBQ=,tag:3M3sl4OgYJ/rgsv7zCgkHA==,type:str]
  RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:1O6+TJDh+9o1Nbg=,iv:erIwSOBPRq4Py7jFDOLJ6GzbnOXB8uSDBZ6ugh/T0Io=,tag:elxvsqPbYB6f4IKHiC0pbA==,type:str]
  RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:3ePK73ND6h5RVps=,iv:TTfMbNv8XdzbVbEIqC1MxeEFRvsbAiamDuQAey1b6jY=,tag:lyq/0qweZ4Dm3KcGmMwkWA==,type:str]
  RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:0VjS2QQ1fjqGrQ==,iv:fRcCL8nNhLOHhX8u9kpXxzAQiIuw32gOHba1bZ62clg=,tag:M7+7/so6Kh2mtLmo0sHuFQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:qxTXR2PUA1G9kv4ayw+h/ytgJLsYeg==,iv:wS5wxkZZfK5KDtZ3mFsWQsu0amcenHEOM6JzCU8Bm+8=,tag:x2gSnzyfnX+zL0LTkPBeCw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:UkgNO5wRyRVlubJcJNJvySw9WpEbi/YQ2UfKgpqjCB0f+/VRLq8=,iv:BscAIN0F0JKLuVGwW9zagi2WPhvJaK/pCd2X08drKNk=,tag:66Fv+qZS/b6MxZob1KWNXA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:OUgtWldv,iv:Q8nZ7HDGsx9vzL0PDllj+XNKD03LMfZWFzPJ8P58zNE=,tag:MD7DZeLnvEPW4BRn33wbzg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:cHP0k/X45iQYHGo=,iv:WY+GvPZZj9ivZ1UwqWXEBTB0UedltSQGm3a5tRQnJSU=,tag:qgGK7p95Ew3FnrLyX+KFtg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:HlLzRxTKvX1wea4=,iv:ng8WBjbT5YB42Ug0szOVraa9XgN7MEYTl9M5GFAVuHM=,tag:4tD/05KgvFdNLXj53nN5EQ==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUzJJdVZxTElhMVk3N1BN
        V1ovVW80cXlqdEdpYzhTWktDdDMzOVN2aHpBCjIzSk1OTVAxa0JyVGpmQmdFS2c2
        aEY1QnFKeklUdktJeXF0Mmg1WmhpMkUKLS0tIFFJLzRGZ2VLYlZJSWQzd1E5ZFM1
        YjZWaUI2d2pkcDROcnJwY1h1a1JuL00KlI+5a6NeGtyCKZG5vDPSUMSiEY4ld7Wt
        qUDaahmakqCGIgatPZkIkT28lrjbl+FbbS+1HR7Lzg2iDKlLkcqqRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T08:24:35Z"
  mac: ENC[AES256_GCM,data:QwFwsxvfymAvQAlL9ymwFJHgV/+CpcW9vqp/Lh3d3t61TzYBQPdaZbpdYKIwZjiAOsrOGX7zb8eIUnHXab037LznLUvGspdhPLJmwpA/r/OmNNsrfZA9m2ZbLHfoCE8oaE4/l7VBdwbA1UC7Nb0Qrlj1Tygs7yET2e+Gyf3q91o=,iv:orBaywQQIq7lsij0virECKqQvZ9WyGiMfLKk8vjrqrA=,tag:fLmE1C29RGRQmhLLeM09zg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
