# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:9vWk7eu7cEbcoaAR8uBvh+daus7mKNeD0Qp7pUtfhSI=,iv:jPNoZ0CdAUiVhTm4MRUZXMenjSNHhVRLf5hl6/ewSF0=,tag:jGZWSQkcrDIN8kIFi8Z9+g==,type:str]
  RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:B/FoLTIabTd4yWGJA9kJdaeH4X4YefGwjo5OEVBku2H2lnIY0aU=,iv:2WfEfh7dmWJ2ORkAVpL1oov0NBW473tOjFmRj5HwhmQ=,tag:mMjWZqUkklndnM6C9uWmRQ==,type:str]
  RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:beSOeA==,iv:LTbAnfP35oLkTmsJTTodS1eGd+0dAwbaJtDO0fXroCw=,tag:hAQxXGREJrY5jl0UjdJesg==,type:str]
  RADARR__POSTGRES__USER: ENC[AES256_GCM,data:MdECNgp0,iv:F/rG+Eo3//VKGQVQj9dg3MM9w9IioPKUfmQTYZo8FBQ=,tag:3M3sl4OgYJ/rgsv7zCgkHA==,type:str]
  RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:eJ5dG7vlzGCU/UUQwsDCshH4RoffLGerlgrxMI50lNvMrFJbIep+BrxcMSI=,iv:1v2t+BHpF/l0XVAVQzT16l7pJFK3WWkBl0Ou7icTWxc=,tag:E5vz49STL9XlWFgSCJuP5w==,type:str]
  RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:3ePK73ND6h5RVps=,iv:TTfMbNv8XdzbVbEIqC1MxeEFRvsbAiamDuQAey1b6jY=,tag:lyq/0qweZ4Dm3KcGmMwkWA==,type:str]
  RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:0VjS2QQ1fjqGrQ==,iv:fRcCL8nNhLOHhX8u9kpXxzAQiIuw32gOHba1bZ62clg=,tag:M7+7/so6Kh2mtLmo0sHuFQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:qxTXR2PUA1G9kv4ayw+h/ytgJLsYeg==,iv:wS5wxkZZfK5KDtZ3mFsWQsu0amcenHEOM6JzCU8Bm+8=,tag:x2gSnzyfnX+zL0LTkPBeCw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:UkgNO5wRyRVlubJcJNJvySw9WpEbi/YQ2UfKgpqjCB0f+/VRLq8=,iv:BscAIN0F0JKLuVGwW9zagi2WPhvJaK/pCd2X08drKNk=,tag:66Fv+qZS/b6MxZob1KWNXA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:OUgtWldv,iv:Q8nZ7HDGsx9vzL0PDllj+XNKD03LMfZWFzPJ8P58zNE=,tag:MD7DZeLnvEPW4BRn33wbzg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:yIredhSDMiqeE5aCjOaB7Y1yyNMrhr2UJkZmrKQmCt2I+XVGcC83PqTycMg=,iv:A6HtaLMVLTxRE1rJ2sZrkKnoJ4zveq0HOB4my7GvqpU=,tag:dvaHtOAV0pc8oWJzTts2Jg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:sjKeVygcrFod13JfHQuzzKSlpDKC7I8B91oSpf6naMFWH06RIIxtZeYbQZQ=,iv:kvN6ovyZmfROJZr1O0j3PmV0DeJ4LPeLePGTDP+BFcU=,tag:1C51iL/5FVbTrZLgL6u4VQ==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUzJJdVZxTElhMVk3N1BN
        V1ovVW80cXlqdEdpYzhTWktDdDMzOVN2aHpBCjIzSk1OTVAxa0JyVGpmQmdFS2c2
        aEY1QnFKeklUdktJeXF0Mmg1WmhpMkUKLS0tIFFJLzRGZ2VLYlZJSWQzd1E5ZFM1
        YjZWaUI2d2pkcDROcnJwY1h1a1JuL00KlI+5a6NeGtyCKZG5vDPSUMSiEY4ld7Wt
        qUDaahmakqCGIgatPZkIkT28lrjbl+FbbS+1HR7Lzg2iDKlLkcqqRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:22:33Z"
  mac: ENC[AES256_GCM,data:QrNS/DVY5k+LMa7Ve+9H1ab1z04MbtPZ2ag7gUMRzFg2hToPX7s2EjOqUwzjc0/2ug3hlLA5DEkF0pJI1wDpbTOihAJzpKuqaBnwvC4S/k2/ygLsu1E6Tq85/dQibBMvWHibL4/C1/3IqyIc+UOoq7dP5O+YhazoN1zDs4VKTy4=,iv:bdGib1YtI22dTFEq98YBd7zMi3w2SYfph6yn4AXWux4=,tag:A3uwvGaoKo5HQmXKyHnNoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
