# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: qui-secret
stringData:
  QUI__SESSION_SECRET: ENC[AES256_GCM,data:dHsiePjXJ8evQM4xeh2bRuSFwfpP1mUzO67ixjajMc6BBdVS67/JpXTUhUc=,iv:eVt/rXXZDaNJj3bxb0fwlIvgJOMmLiGJhVbeo9kXyAg=,tag:mUqriAEaYaTpLn3dVtEmaA==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMVpqTFhVT09POWRRNVpS
        MFB2SWM1dWRxcitybzFPVHVoeWJKYXFOYkdFClErd3hDQWlRL3BXVW04WFh5S21D
        a3VqeW43TjBSRzRqckJQN2NBNlRaWTAKLS0tIG1NVXFJQndTNU83T1lyenhRSEtJ
        NG1ZdmtNZU00WWtidUZtL0ZwUno2aVEKsVAylJ5+tgkzvuYxMCUGqtfEsOkTTF+K
        Z88N15xyO88YpO2T7SrfCNx1b9blQ1EBV1y2i/c+JseNuRHJ60ltkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T10:34:14Z"
  mac: ENC[AES256_GCM,data:+sKOz74+T6xAnIEjbQP0fAXeE9HTISzp355uJuzsnJSSA7C/etAFEdj/H2rrHrCZft5dAQOACPDUd/kj41GKBOdMT/34aZMuANBwUH5uZS+sWvshEenP8mjmu56EP5BnnAB+kL8bfLlsqWrLwOc7NgIYAW/o431TCjNoHfmHrj8=,iv:7BzitkNdSdvQM4IQ09y+nH1hEAjdbstI6nvJrCrksOs=,tag:k2HmOAypdcBzjUiO6q1vRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
