# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
stringData:
  DB_HOSTNAME: ENC[AES256_GCM,data:atIWwobtRz56lMkISPbWa/BmhQ3q1WL7jTScZ0eUDQ64gmn9LJE=,iv:/iQLw/aeMxkOCG7TsZCD7FDA+U+3X4DNu/E6DJdDUgc=,tag:XfUfSA4U+YOww2ZH3jQKaA==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:bhtvZCb+Sc4=,iv:jC4lzUA7U2s3b5tBNYDTK27OqU7RY4bYzRzzCFjGHYc=,tag:CiQmQwF7BB+Jkm6UcoLNRg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:Ddj6Q2mN6zL49WA=,iv:3EGRxQir+9nUCp/UqoWYXuClqpMX07Woi4h5Nb+/UF8=,tag:MUB/lyYNEcHo/2bQ5Om3Cg==,type:str]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:7s8rugOW,iv:vXdONyXhQwA6Nf6zPHII42w5U/G0dFq2cEgAFmVRXzA=,tag:ebJEO8R3WEt+Px2CmI2xKg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LZ782dNQ,iv:a+3oiF6yVNyJupXsiJyNZffzyv6vtleevRQHyk94Y2Y=,tag:SQ91rF+sUbMNWpF85G+iJg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+lU5FTyrPRJb2H4on5orEDZbnoRXT/yNJ7yiP6kjjVdUb/dP1do=,iv:EEWzi2vwIN5H/zc0xzyayDNcfkdXbNWd+dItVignKrU=,tag:eG4NBwLSjekWhQzB+AzYdQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:ps/pRFhD,iv:/8tfgF1roGPQI9W5zEUIPSekFuQ5Zl3k5X7ejx0J1D4=,tag:8Ql3dhizNZJhX2XTlNrG/g==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:b2da4jxIMVzW5FQ=,iv:hu/3l1VNYF+49oIYGAwcASUQxZkABKkuTD+vw1yNWf8=,tag:D7ZORkTfVbz45ZqpqjrAOg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:yL1rpnIiXonPnoI=,iv:KNVPWZ7OnrcB/PDE16iBfe70KYI1Zs3Vq2EBHhaBoGw=,tag:kp/0RbWM2it/fKwD5T5Qwg==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUG5OdmgyL25MTkJNMDJv
        ekE2ZGFheHMvTUd6UlJNUGF3T01NRWdpMkhRCm0wZjFMRmM4UUVnK0p0RWcxdHV5
        Nk94RVB0dERodnRPZWJKZGZ0UVNPbE0KLS0tIDc0TE9sR0VadXp5T3JTYm9LUUM0
        ejY1MDBrT1hyS1ZCVnBtb1phd01SaW8Kq5BH4Hpf8veBVB/8SQq9CdIp2gHU6UCb
        qxlRqlIuWvqtB+HcnB5xu+JU/68Hi5c2/mFtDJGsGpYg6LvKSQ0nKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T08:26:02Z"
  mac: ENC[AES256_GCM,data:/Kw+wO/C4PDTx+9MfPKMg763C4TCPv74hlpSHc3kkCoIn1i4mhoNxJ941fZLeISHHTh855/Oo/45c0ANVlXQbpUPT12Dc/Uc+AiSSQU36yNTnjIykSr9ExSeOamGXMoz29xaQml36Fq4Pp+JFNJiGQo1eL6znfP6hlwpUneXAMU=,iv:8+nyFvl7kJ19I4p4gV8TQtfWFYgppToq0bJNRfpKJn8=,tag:uE//4shr/BGv4ckmd13Tvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
