---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: a-379-store
spec:
  secretName: "a-379-store-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: a-379.store
  dnsNames:
    - "a-379.store"
    - "*.a-379.store"
