# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:OlJSKEkZS1T0SCB8njMkb1Z/Y26EDJ4PKsnhKf8WTzw=,iv:P4BpFSynx+0ewQm10QTzrNyn5xmgR2ZKoAaSc/yvNyU=,tag:PTvixlFng412mdMqWTKEAg==,type:str]
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:tGOrL9MVZUgvj5sKtfUTf671m5puSFyWlWlQiwMbgw6rY4upnf0=,iv:LeMwoeP87HQlj6Z3slsdvIgNR/BwmGDXpPsa+RfGEy0=,tag:39vgXY9EZsnNh0kbVfO6zA==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:cnxTHA==,iv:m9Qbiflsj/x8eFCGqliwoO8n18vRaqzvPFhe6srrgbM=,tag:RmIzKePc5dHI8Znq3XzZpw==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:DbH2WJus,iv:inQ2Mz4C+CwpJX+40qQ9/q+gz/W1pID4hLUIQCaQsIE=,tag:xlQ20OFEhnfoqtGw/b9TJA==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:4PcjBlMbtEu96CkVXxBHOhTQLLuULhuFUs+ThxdJdqXBwyLjyPEiNGr5Z8o=,iv:u1lYpAM/I1SPFvdzp52xNLzHRGVJhr1aTcLWE7LbSY4=,tag:PAhJBsC5HnZ9sUOVvr3AZw==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:uvLyipX62YQcA2Y=,iv:1vzv6dxueeJJKFAxGW+o8MTOQgw5IKszra01ewvdk3w=,tag:pDxE7bVMXvIcT5hEnSi7rg==,type:str]
  SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:Z5KC9zwh8mTINg==,iv:RIzjcNuxrI3SJ7/Id7IxEIVJ+eg0h0Qanh/DGraE0wA=,tag:bNyPCLpwR4Ge+bAgRi1psw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cxT0YUG7r/Gu/vBAO70twpR36d5xnA==,iv:d7jVX+fxcauzxsurKwkkb3Xef8nTmG6HBj8/yUqn+lM=,tag:7e0jQgVmeKv4QBqkqe4VdA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:lmJgjB6vHKI0kqncjzu4q5i5nvnDdCfKiZY0AHqcShpfYRznJFY=,iv:o+MxwAivNY8WXmsTc/GX7qga1SjD4DAlNZSjeCMevlc=,tag:ziYOvGpazLR48QZP81p+7A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:sMrEx5ro,iv:fA/0rlB9G1I8lJNUP8EEFrLbPjd0pf5vLY/q6+Q/Hv8=,tag:EI28dTjO8d8o0piuxtIFtA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:i+Zi1lpPVEueq7Xt/5UOEKTFw8MTHzg7Csrza/F6cusKcHmV5W0gGE6dc8Q=,iv:4aYhc/KU513SUlEW9pzriaY4286tpj2tWTc/XS8r4ug=,tag:QkJOVJYs6fc0g+DAwtMeqw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:WRRk7lBzACP1y5w/gIHxHuGAv1SYaVQ0LS4ZMwtdWYhzDQMzpWcA+VjYAc8=,iv:KIv9w00rvOm22Rz1BBjDtPQw05WR44Mbubrsv1Boups=,tag:S4jIHxUaB9U97eBpw8Zl1g==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQi9GcGZpbFlra2tzSWtK
        RnpWWXJ5NURpVXE1bHQrT2locy96RGpFNEIwCmFtT0RaZWw0Nll2MTN0WTN1OWVE
        RGN1OVlBNW5hQURmTHpseFBxQ0hrQXcKLS0tIDJjOEtqaTkzbmFiVkJHbHk3RGE5
        MzJMbU1jN3d2djhKdFVjcTRGSTJEbjQKRnUWIggnGyZ9g6TQ4LpIvtwjKCxTQCo2
        pgSVDQPtLxVnZNapgy3ciEXZ3pd5f5efdPKySx1kOz9BJ2s69U6Mfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:23:04Z"
  mac: ENC[AES256_GCM,data:Ntzt5Hu7698ekMx1zhV+Nw+FyIVIsdYA3BQ07ZsxmCIH2czQhYm+h3PdDjYKVWOlIb5C7YF5TVK6ZuXq0q3ShPrhirKU1Fs1LrVz8hW8sT9hxud5c+LnqvcZ4mOhD/zmeJ4L6bDzr4Do5cEac1Bi29tinLKt3l52bDIzHmxUAHU=,iv:3ltgmsLkY4gQkkAW+/stejDedauxGN6F99T2XvmsR5Q=,tag:bnWxmk55LJUb09NAsd/t8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
