# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:OlJSKEkZS1T0SCB8njMkb1Z/Y26EDJ4PKsnhKf8WTzw=,iv:P4BpFSynx+0ewQm10QTzrNyn5xmgR2ZKoAaSc/yvNyU=,tag:PTvixlFng412mdMqWTKEAg==,type:str]
  SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:tGOrL9MVZUgvj5sKtfUTf671m5puSFyWlWlQiwMbgw6rY4upnf0=,iv:LeMwoeP87HQlj6Z3slsdvIgNR/BwmGDXpPsa+RfGEy0=,tag:39vgXY9EZsnNh0kbVfO6zA==,type:str]
  SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:cnxTHA==,iv:m9Qbiflsj/x8eFCGqliwoO8n18vRaqzvPFhe6srrgbM=,tag:RmIzKePc5dHI8Znq3XzZpw==,type:str]
  SONARR__POSTGRES__USER: ENC[AES256_GCM,data:DbH2WJus,iv:inQ2Mz4C+CwpJX+40qQ9/q+gz/W1pID4hLUIQCaQsIE=,tag:xlQ20OFEhnfoqtGw/b9TJA==,type:str]
  SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:tz5sPbouH+5lgYc=,iv:Jy/A33yHW770Z2UiHj6qVfcCviDUGYFLFmNuqMQoRpA=,tag:lv8+1fJCyw1baeiKSZLUTQ==,type:str]
  SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:uvLyipX62YQcA2Y=,iv:1vzv6dxueeJJKFAxGW+o8MTOQgw5IKszra01ewvdk3w=,tag:pDxE7bVMXvIcT5hEnSi7rg==,type:str]
  SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:Z5KC9zwh8mTINg==,iv:RIzjcNuxrI3SJ7/Id7IxEIVJ+eg0h0Qanh/DGraE0wA=,tag:bNyPCLpwR4Ge+bAgRi1psw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cxT0YUG7r/Gu/vBAO70twpR36d5xnA==,iv:d7jVX+fxcauzxsurKwkkb3Xef8nTmG6HBj8/yUqn+lM=,tag:7e0jQgVmeKv4QBqkqe4VdA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:lmJgjB6vHKI0kqncjzu4q5i5nvnDdCfKiZY0AHqcShpfYRznJFY=,iv:o+MxwAivNY8WXmsTc/GX7qga1SjD4DAlNZSjeCMevlc=,tag:ziYOvGpazLR48QZP81p+7A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:sMrEx5ro,iv:fA/0rlB9G1I8lJNUP8EEFrLbPjd0pf5vLY/q6+Q/Hv8=,tag:EI28dTjO8d8o0piuxtIFtA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:mSS1z2CNiCw8pr4=,iv:ZQybSAKguT8BwJlkti+Cut9Oryu/YsEVOEkYXNOsI4I=,tag:7rh7ssC2jtBcSiqIyz/4Nw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:i31Sc/HK9GMulrI=,iv:UCojMAZ6UhfEsdoai9WHPcT7OzrjIVvMzeFDK2CBpuE=,tag:fDJAs5BnFnAf3a8iEVgJBQ==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQi9GcGZpbFlra2tzSWtK
        RnpWWXJ5NURpVXE1bHQrT2locy96RGpFNEIwCmFtT0RaZWw0Nll2MTN0WTN1OWVE
        RGN1OVlBNW5hQURmTHpseFBxQ0hrQXcKLS0tIDJjOEtqaTkzbmFiVkJHbHk3RGE5
        MzJMbU1jN3d2djhKdFVjcTRGSTJEbjQKRnUWIggnGyZ9g6TQ4LpIvtwjKCxTQCo2
        pgSVDQPtLxVnZNapgy3ciEXZ3pd5f5efdPKySx1kOz9BJ2s69U6Mfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T08:24:20Z"
  mac: ENC[AES256_GCM,data:fz1YaA6DybPmGPTU+VNZ8cbZ4YvkzVyUSoBUersU/Z5XTC0jKcHXw2yBGcNum4Rty/xQ0vZ7OQnDygIZUvUmdaeccEf9scpYf00MlEjYfVhhFeswy3WKMx5q5T8zPt6gebWgMCGo+mbetfsehZ+1+3tKeSjd8JMP1/6eBDwuH9A=,iv:D2T8UigNIgiyjbDBbHIWzirVxx/WAyMHolaKTqX9hqk=,tag:j1lNLYHoi7bjH+48vLacXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
