apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${APP}-volsync-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kt1oXz36nUoiokNpD50nQzcnLhWshuG4hCQsBHh7OYE=,iv:7nRohN/mT9A0LueN4jFqtnA+mIoTPXfB+bKrvWsA7uQ=,tag:Jzb7n155KAHtT73FWxncmw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:94Aj2K56aH2KCgI7VYamUAP229s+BKFc3fLAp8qAthWK48/rqtzjAIEQFTbLqBgPKW0jTEGDYhvCWnQMbDQ9cw==,iv:2aaZkbCDKoDpgqImyXZQ04mXcOeZ3qREFk0hdojGsd0=,tag:vqiOCn45Ia4ERgV6pzOv7A==,type:str]
  AWS_S3_ENDPOINT: ENC[AES256_GCM,data:wcihv3ij4y6HTF3uCcN0IvRka7nWmgugH5ImNh3ZBmoxcwgMA+HHVM3jDof9eFkFjd1gUXhdfa0Uq0TFx44UOrk=,iv:PpNSzvuyzMzxMQPNnzvdIRNkhV88GIdOE6p65C47Tnc=,tag:kbv4BYIP9nLtOPYRv9bs4Q==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:l2UuI9+FHDbdIUuenwynrw==,iv:cD+iQUSnN2WAPurHg4sYSGEpPicM/z0rRSSLdsPw1+k=,tag:OAZrRR3Ui1YNOTv7ZyUO1A==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:msId+DPwGsqqkOyZVCWJ2Gc=,iv:+yYrRZ+ipkKOQxPTOk//Z1Hqeue2nObFlfe1R0P9SEo=,tag:N2b/k8XcyTPzx1sXweqZjA==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb3VSK1V1SnJuZE9XMmVQ
        K05DenJtVHM0OFNLL1pmeUdEalZKZVhDdHhJCk90VmtDZFd5b3FOUEVnMklqYkFp
        WkJNRkV6K1lzTzdZdlJXUnJVbUNsVWcKLS0tIGtpc0Z0d0NyTEZpTVhwTzgwYXpD
        RCtMZmFnSXQ0SlV1S1YvNm1ab2hrRkUKvVuqhbn9xjpmiSYtKsG+7ryhznTqyqVt
        Lqfj3ReOnvOdAQl/8IKOS5sBdfpCpR2ULir+rAxxIBizQke0n9uOMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T08:15:48Z"
  mac: ENC[AES256_GCM,data:Wcxdp5vWLZjkFUYo2QYU3yqGr287FmQ5gH+qktY6wSJFTUoLrSUDzYEpYSCeF/RgvAXdUNTy+bEPoZPmKPdj+5oSg1wh//+YFqJMAxTIuM15meqINVAbgD74sahwMsqByMRjUJCoeg9t4+xnu/hQlrzY4ccgk5KCDsrjmUkMjGQ=,iv:0SquztE4aTwxNUpa3atS5GERWUfzw99eJ85Zt1SpeR0=,tag:xebp5WCsdwd2J5EenEvZLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
