# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: kopia
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Fa9K4SbEGqZFI1S/uTbQHg==,iv:Xoa6POwKqLTrzEM2b8JfVyhnyz/ymvU6fkG3wUQZ4i0=,tag:ajoJSw4eyZ2oiDdHb9fmoA==,type:str]
  repository.config: ENC[AES256_GCM,data:Yk1apXam0OHeb4n4aGcu9YZSWDLcxRo8+xbPeLlID7O0mTHs2spSSZh+8o8cDyaoQGq2il3Q6cTY937+/+u0Lfc3587kfnT7QrmMAikHqqT61FqCxiGbEsQsjKs5pwjIpmGGfvFYqC7rSGrurJS1mXWP7pgRYVgH4H8W1u+2d7UgoTJth7XFth2HYQ49wQBlp2KW6qCMftXaA4wHdwlyonMBLSQcelPU0jbE4eK9Upjo8SyysEt0Q6gKkx6nWPbmQ8kpd1NM26uFKCj1ayhdpiyAYkPgtmXHFQnKxg0AFmJtgrLE3nxLZBkH1xa2/zQ3E6nQZTh4C1TuBAlIxGxbeOWYvgG65Wmy3BMKiQz6BvdaGDp/roKgwP9pLLzKxBtDR4ZjWdEtIbVlrbm3Fq1IVEjBnXrE+D/l9W/R6FAd3fofP4SpxG+fIfi5qKl7t2bAeoMTvwXMKOi08Gb0DIdPSFuam3n1KopTTJ7IgbIthGjxllueIa5sh9tIw0zjv4auUgJQsFW5pJ3abGbz6cxjNFtf9JkccwiHW6ajI3fLX2nLr95ETI0OXE2f560jb5jkZfgvomrEGvYyfIA41s1T6GuKpvV5NdYekx+v,iv:fSkTmY091l7rHsEEtnfYqC3lqXydHKve+2qD2CbARvQ=,tag:n2ncaNjQBS7q0uXhNAxHiA==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNk1jM2lZZis4Y3hJMGVs
        aEhkT3laaXNsM1BNUUI5bnZpNVl2QnBaVmhRCmxWRi8zaTIxMFlEaUVnblQ0WllF
        Yk5Gem9RSXlROHRWNVo0aDJNQVVnWFEKLS0tIFRmdVh1ckduTXA1bkliYlA3cTZP
        ZzE1MGYyV3VCMUQ0WTc3YWZEMXl4cjgKFI2d4brqDxFKKAGhRSHN/26G4qO+QDud
        l42Y5wcvoIKmPMP461ClA/jbH9L4iPzUO8bhUnJbnuU984b+U/3KDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T07:49:46Z"
  mac: ENC[AES256_GCM,data:r6NNLHW+U2cAzpQ7x/nSJCbdzOwgzpQxHYel8xYYwrY03fPyK4Cy5n8tvi8Zil6aFYe0P2kY+yx4+3FcqGu/Vmk/ONwkUBHw538JDiAy7ci+UaK4bnrGu5fxTP4AXbfGlcawpVT+5sCGK5Kt+RQqlL+FL/6ahiC5oaOOXitRph8=,iv:ZrRnU/9epJoET97swtAjT09QCyfvXEqGWvzuVzVlmGg=,tag:tl1nQOupd8UJ8ysznJFAtQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
