# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: atuin-secret
stringData:
  ATUIN_DB_URI: ENC[AES256_GCM,data:Ae3WnwhAeo8w04TGD3b2FMoSPjTBhRjCxHGT3xW+qrwkQmHhf9ISr38VvI9U3KBfZjzJDVwpbjpzEKMNkTNWHe0a9rIF0ET0jC49wPE5sysKLiYwVaqziryf7OfcedGJ9mHbJr8LdrY=,iv:VMBZj4HudyvZpL+/R0ZAmACTCHbCZKwwTKwqUMU0a7k=,tag:MZJStqBCayykOENQHc1spA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:C3Esais=,iv:5xErRZk7/tyGcrifUpBH9rwfYkAgMcHGife3Y2YK/jk=,tag:DIywWr5HgA37pwZfRuwUGw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:HNN3ZKzMReNvqmqVOOMG3i/F7jJH9iMYMcCEOEP7ceSSkoIa3rM=,iv:9cizioqLN/Lc7DUKrnEr3nbOcQG3pKX9nRR9glL7gz0=,tag:/DHVtjTTELWNCs/uJ5ZMuQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:iT/e6GM=,iv:qIhOzWNUp58M7l4TXFJ+QhK4uwxRJJgwcXDIEpAoznE=,tag:bkaZ0V+EDOP1F+sVlZ/iSA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:0+inhm1bwAqxy2mYY50ISGhPs9UbGYsza2S24e2UiYPSaWyL6BJXFJjW,iv:JUQ1wERQGbZ/OQlxgWM1aQu6cxudLzSb06Ao9H3xf7g=,tag:/qpkA75+KmblJUCNRbToFw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ZdMwnryhO2MFr3wv/BwpTqy/mYN/0GGUVOJRuOasonNl3l1IwMrQl8iUnMg=,iv:A1446lUik+D2xBxOAcTNMvxOlSRMnMCnU/gG4VhgjAc=,tag:VqLrveQEuu1cgshukW2jMQ==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbXBTNnJqb2dCbTNORWIz
        NldBMGhUQXduMlF2NGNHN05ibGtpVUdRNWw0CmpJSE82ZkU1Ly9HWGdmZUllMWUz
        LzZWUTZYR25icGxGZEJ6cGoyWDVHRlUKLS0tIGJ4S0lFMDZ5eFdLVVFKeVNjazk4
        bWRNTVQyTHJVYklQakJiWVRKcEQ2NUEKJH25yONr688m3kT3jsZkpgOCozV5OFtL
        VkjB1n6jicRFEd7AQyk2G4pomtZTCXK9nwpbxmeuaKGg2uR4DL86hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T04:49:51Z"
  mac: ENC[AES256_GCM,data:DppOxMke/xfjkgAFbC2ES42znWPVutVGNlqjI8VWpfDdD0yIk5XEfj8go0wEdy41MohGzN6G9nGqKnA6t3umH8CCS2H700X+it6R3I5qptzkEHTBL2XCu8Gybv18pIrAB5LrGuDO8lwyHgOkkKxJjCAiYLr9oIiZ/Z/r7kpiaYc=,iv:M6HFnX56DUzMZVVZGXd1tEONem146RVZYTksTA+gr8I=,tag:rNlKHiptgoCbzSjJ5GCBJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
