---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./replicationsource.yaml
  # - ./replicationdestination.yaml # Will implement in the future
  - ./secret.sops.yaml
