# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
stringData:
  Logging__LogLevel__Default: ENC[AES256_GCM,data:Z53Vp7ZDaeHq79s=,iv:DIqC23C0EVS5ZTy7U5vr9Pucj7PZWPp90U/0pa22XnU=,tag:Axsvxs2Nmb/skk0+oy4rjQ==,type:str]
  Logging__LogLevel__Microsoft.AspNetCore: ENC[AES256_GCM,data:5cEo7PNCEQ==,iv:yI91yI82zfxvYGXKCxkTNaoyr0Sg8WVWsHMJJoWhM2g=,tag:N6BTRxSi5q05I1tV7HffAQ==,type:str]
  ConnectionStrings__identitydb: ENC[AES256_GCM,data:bpyJaVoQzKMvfVNT1OevZeqNJAy/doldGPQg6fpSJVX8X7l/Jlq7md1mHQOFO2C1h+WAOc0PAyp7BVxU/+Azl6qUnqwzRE2whkuMlXDO7s6tVI+GrfJ+61flN3vcDeA+nsvt37+d1JZVBzife7VPupRlI7Jlb4hZE2StyzuR4Oq6TqLPxTNrQjNzBTx/TGR0HMeFSPCm4RcbHnDntPA6XtcB1+E=,iv:V3NO0ZHevj/3TV9WfLSK6F/E2pazkNJ5qp30mfoIN5o=,tag:/6EjKS3CLUGpZwy/UuY6tg==,type:str]
  ConnectionStrings__farmdb: ENC[AES256_GCM,data:ESU3c4qk0dAKD4Gih9nk0yFTxy9ysKvlpWMEV5zmnR+OlYZtUB+5VVwUR3RBG3hHa79MjNcaTCTbDcKWOp40qRAERSGRN3yx6s82RFhAZSj42gMFuJBVsJawFTiNQQa8XFoGlsvPzVLcpCIgjR9yCSWnVt3JiAxfo62g0gJpYHl5TfQA2OFGtfYtYFrfr74VyjdfVqCZH7iKzzIvWsc8kQ==,iv:7S1zQsk60YnZUc9V3N2lODgMxwmuFjJg3Ujl4mwRhwI=,tag:jfWo9ZIkCRZNnYJup4fJTA==,type:str]
  ConnectionStrings__auctiondb: ENC[AES256_GCM,data:wV6jV0C3Zh1d0sDysP38olculcdlJhtI1LO4eegH3/YyMZpGdGFzUNaN5f4tv1XW2AIIDGpsIsIfV8lyrzyyqv2ddZK0l1eM3yUlRX4UsZxd2kb5pWDcNctzkedgpG2j8L12MwyPJoLnXzWh4GQjErYqjqz1oqDff6ucaqYVB0rMq1dtM8VPgFN40eyuqqBLdQHLmHaQdTEULKoPd8NsxaOKcg==,iv:v5jcZ/hrqWv0AjW0iVknUoRK6THA2KOrlk1PWapH61I=,tag:4Hu+HW70hOLfJOSgX2FYrg==,type:str]
  ConnectionStrings__workerdb: ENC[AES256_GCM,data:YJW37qDB8hqqtThq2/0H71E2cCJgxderrbdWrmqV96Et/OXiEAIaoehdFBoSKQIFymiRJGseSAazd0MY2u6/rL4d3toBdJwn+wBgrzj8nHNwbp0G+G7ufdE2Qt3aEmVTU8SzETjnWzVa3e1q91FlQFKQUOyIk2Wvfb2ViCecp+EvEGrzg8i8RJh8k17ZGU+senJRfZt3wdCVyC4UMudx5wIB,iv:/ocxtRs/FI/2Lll5YMMoinEobAl0oLeBWlwWDKNKutY=,tag:QF73TMYWFIPZ7LAdOuTDCQ==,type:str]
  JWTSETTINGS__SECRETKEY: ENC[AES256_GCM,data:cfMaazocLEjy18NQH3Vgm9Q1wAsQmCzgzAqhH1OhOZc0bZtcpX9ZHpJc0PfU6j9AwOzk/bfz4XtGrqTuRX+JhVdP/kwJ5xZr2Xn/JvrEfRV0hGslqs7v/mBXpxUNiJXcndwSv0Qf8dSHQZAeWRpiPtErRQUH5XR1XARXAbqrkcajzUuWaLMlndK5nsirRA==,iv:dHEDixolep9sG1aC/45FTVAtkh/743An4uYWHLu3/5k=,tag:qlqzzHTrQhAQ9fyywmccwg==,type:str]
  JWTSETTINGS__ISSUER: ENC[AES256_GCM,data:PCA00rnqfk7jUrJ/tyKAfRJuDOpCuDWZSQ==,iv:S+YYOjw30+NESqNvlhBeU+DrFUCDnhWIqASiuKHPWVo=,tag:mceK3QnUgSaqHuCHUGTZWw==,type:str]
  JWTSETTINGS__AUDIENCE: ENC[AES256_GCM,data:fquaniDIeiA31IOLOto=,iv:VsHaLdGQ6nUHqR7TpbjPbDWEEIdCXx76AksKW2cksYM=,tag:qP/8B8tJXQiy7HspIqijBw==,type:str]
  JWTSETTINGS__ACCESSTOKENEXPIRATIONMINUTES: ENC[AES256_GCM,data:ZAU=,iv:mUXSekZWILujcRiIwgMSxr5LhKH2q+bPCW2yxVQCVRc=,tag:Msqv/mKCi56jfWfkKMtXGQ==,type:str]
  JWTSETTINGS__REFRESHTOKENEXPIRATIONDAYS: ENC[AES256_GCM,data:IA==,iv:zRtu8r1Lokg0+zmPMQT7NIBH4L6rMOin8xDz8x/ozsI=,tag:6Y9khXR0SKu2AdgQKJzHRA==,type:str]
  CLOUDINARY_CLOUD_NAME: ENC[AES256_GCM,data:dYbxF9Qa6ENc,iv:QJ5O3rEVfhXQ8qKdJ1U7tEfVzd2zgnVIFh7RzWb1wnA=,tag:CQSp7DW/r7z13796sc5lhQ==,type:str]
  CLOUDINARY_API_KEY: ENC[AES256_GCM,data:kAmEYlMXgJABqp8FIS2F,iv:ckju0PKOxqkJ3lbNAx1OJvQb1yZaw1xky4HlRz00eIc=,tag:jrjqFynrh7t0KhnuC896FQ==,type:str]
  CLOUDINARY_API_SECRET: ENC[AES256_GCM,data:GaY7JFD7DL8amDyR8Den+QbWL9OKGsyVw0PJ,iv:eDa6sSU04VqMARZ/spLAbHSyMOvxnoGHDETaLMPmSIo=,tag:OjSs8TqWfuzJUxwCJKx9DQ==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRlVLYkNLd043UWhzc3Rs
        RndHd1NVaWtiZXBiNWNiQVdyM2N2SGR4bzFJCktEMFR1Z01TeTlVZUhsdUx2azNN
        STNyN2hnTG9rdGtIbmYvdklnSTUrSHcKLS0tIFhvNXRpbEVnbzVVdFNya0tBcnNE
        L3JnMk10NHBaZHMwei9qOGJzNDJSakUKfG363YPsBqcPTqLILl0/azNiC98ssOpC
        jzo2ler5w6JR33EP0cjo0sBnRfzGfXP12zADSfa7sEygpBjuo+a4EA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T07:52:32Z"
  mac: ENC[AES256_GCM,data:xAsWcFKmj4owriQR1OQj0U9kWPb1sJr0W280sG8GCiA61KijdHp0ySEdgJyOyCSA7DNSwsG1kHuVIu2NjUcDhjN8Z8je4gA0NVDXiOdOfThaAPsZGhuIsPrs8sJsko8BozzH/0DYeq7dB9QkjaYAfFyWvAwVm3jfEKMw7/yLHqw=,iv:zEZKu+NKaqIaeFcO60cqYz2Apzn715HO40+0W1XawU4=,tag:ib6IRVyIuzMdjMdR/mWvWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
